apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: infra
  source:
    path: charts/clusters
    repoURL: https://github.com/MoranWeissman/msd-meetup-argocd-2023.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../../values/clusters.yaml 
  syncPolicy:
    automated:
      prune: true