{{- range $index, $cluster := .Values.clusters }}
{{- range $i, $label := $cluster.labels }}
{{- if and (eq $i "datadog") (eq $label "enabled") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-apikey-secret-{{ $cluster.name }}
spec:   
  destination:
    namespace: datadog
    name: {{ $cluster.name }}
  source:
    path: charts/datadog-apikey-secret
    repoURL: 'git@github.com:MoranWeissman/msd-meetup-argocd-2023.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: --set clusterName={{ $cluster.name }} --set annotations.avp.kubernetes.io/path={{ $cluster.name }}
  project: datadog-apikey-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
---
{{- end }}
{{- end }}
{{- end }}