apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName  }}
  annotations:
    avp.kubernetes.io/path: datadog-api-keys-integration
type: Opaque
stringData:
  api-key: <{{ .Values.projectName }}-{{ .Values.env }}>