# This template creates an ExternalSecret for each cluster in the clusters list by looping through the clusters list
# AWS Secrets Manager secret name is automatically prefixed with "k8s-" and we set a variable for it
{{- range .Values.clusters }}
{{- $secretName := printf "k8s-%s" .name }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: {{ .name }}
    creationPolicy: 'Owner'
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          {{- range $key, $value := .labels }}
          {{ $key }}: {{ $value }}
          {{- end }}
          eksAutoMode: '{{"{{ index . \"eksAutoMode\" | default \"false\" }}"}}'
        annotations:
          dd_tags: '{{"{{ index . \"dd_tags\" | default \"\" }}"}}'
          region: '{{"{{ .region }}"}}'
          accountId: '{{"{{ .accountId }}"}}'
      data:
        name: {{ .name }}
        namespace: argocd
        server: '{{"{{ .host }}"}}'
        config: |
          {
            "execProviderConfig": {
              "apiVersion": "client.authentication.k8s.io/v1beta1",
              "command": "argocd-k8s-auth",
              "args": [
                "aws",
                "--cluster-name",
                "{{"{{ .clusterName }}"}}",
                "--role-arn",
                "arn:aws:iam::{{"{{ .accountId }}"}}:role/<YourEKSAdminAssumeRole>"
              ],
              "env": {
                "AWS_REGION": "{{"{{ .region }}"}}"
              }
            },
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{"{{ .caData }}"}}"
            }
          }
  # Fetch all properties from cluster secret
  # If eksAutoMode property doesn't exist, it's simply not included (no error)
  dataFrom:
    - extract:
        key: {{ $secretName }}
---
{{- end }}
