# This ServiceAccount is used by External Secrets Operator to access AWS Secrets Manager
# The IAM role attached to this SA needs the following permissions:
# - secretsmanager:GetSecretValue
# - secretsmanager:DescribeSecret
# For the secrets used by cluster registration and Datadog configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.external_secrets_sa_role }}
  name: external-secrets
  namespace: external-secrets