{{- range $index, $cluster := .Values.clusters }}
  {{- if and (hasKey $cluster.labels "datadog") (eq $cluster.labels.datadog "enabled") }}
    {{- $project := "" }}
    {{- range $mapping := $.Values.projectMappings }}
      {{- $matchFound := false }}

      # Use regex to check both prefix and substring matches
      {{- range $matchName := $mapping.matchNames }}
        {{- if regexMatch (printf "^(%s[-]|.*[-]%s[-].*)" $matchName $matchName) $cluster.name }}
          {{- $matchFound = true }}
          {{- break }}
        {{- end }}
      {{- end }}

      # If a match is found, set the project
      {{- if $matchFound }}
        {{- $project = $mapping.name }}
        {{- break }}
      {{- end }}
    {{- end }}

    # Generate the application if a project is set
    {{- if $project }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-apikey-secret-{{ $cluster.name }}
spec:
  destination:
    namespace: datadog
    name: {{ $cluster.name }}
  source:
    path: charts/datadog-apikey-secret
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: --set projectName={{ $project }} --set env={{ $cluster.labels.env }} --set clusterName={{ $cluster.name }}
  project: datadog-apikey-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    {{- end }}
  {{- end }}
{{- end }}
