{{- range $index, $cluster := .Values.clusters }}
  {{- if and (hasKey $cluster.labels "datadog") (eq $cluster.labels.datadog "enabled") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-apikey-secret-{{ $cluster.name }}
spec:
  destination:
    namespace: datadog
    name: {{ $cluster.name }}
  source:
    path: charts/datadog-apikey-secret
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: --set clusterName={{ $cluster.name }}
  project: datadog-apikey-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{- end }}
{{- end }}
