apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: datadog-api-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-key: "{{ `{{ .apikey }}` }}"
  data:
    - secretKey: apikey
      remoteRef:
        key: datadog-api-keys-integration
        property: "{{ .Values.clusterGlobalValues.projectName | default .Values.clusterGlobalValues.clusterName }}-{{ .Values.clusterGlobalValues.env }}"
