# ---- Kyverno EKS Auto Mode infra-karpenter Overrides ---- #
admissionController:
  nodeSelector:
    node-type: infrastructure
  tolerations:
    - key: infrastructure
      operator: Equal
      value: "true"
      effect: NoSchedule
