# ---- Secrets Store CSI Driver EKS Auto Mode infra-karpenter Overrides ---- #
linux:
  nodeSelector:
    node-type: infrastructure
  tolerations:
    - key: infrastructure
      operator: Equal
      value: "true"
      effect: NoSchedule
