apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  clusterResourceBlacklist:
  - group: ""
    kind: ""
  - group: ""
    kind: ""
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: cluster-addons-root
  name: cluster-addons-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: infra
  sources:
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      path: app-of-apps/cluster-addons
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: -f ../../values/addons-list.yaml -f ../../values/addons-config/defaults.yaml -f ../../values/clusters.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true