{{- range $index, $applicationSet := .Values.applicationsets }}
{{- range $i, $environment := $applicationSet.environments }}
# Create a project for each addon-environment combination
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $applicationSet.appName }}-{{ $environment.env }}
  namespace: argocd
spec:
  clusterResourceBlacklist:
  - group: ""
    kind: ""
  - group: ""
    kind: ""
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
{{- end }}
{{- end }}

{{- range $index, $appset := .Values.applicationsets }}
{{- range $i, $environment := $appset.environments }}
# Create an ApplicationSet for each addon-environment combination
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $appset.appName }}-{{ $environment.env }}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
    - clusters:
        # Select clusters based on environment and addon enablement
        # This allows for selective addon deployment across clusters
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster                  
            env: '{{ $environment.env }}'
            {{ $appset.appName }}: enabled
        values:
          revision: '{{ $environment.version }}'
          app: '{{ $appset.appName }}'
  template:
    metadata:
      name: '{{ $appset.appName }}-{{`{{.name}}`}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io      
    spec:
      project: {{ $appset.appName }}-{{ $environment.env }}
      sources:
        # Primary source - the addon's Helm chart
        - repoURL: {{ $appset.repoURL }}
          targetRevision: '{{`{{default .values.revision (index .metadata.labels (print .values.app "-version"))}}`}}'
          chart: {{ $appset.chart }}
          helm:
            # Load cluster-specific values from the values directory
            valueFiles:
            - '$values/values/addons-values/clusters/{{`{{.name}}`}}/{{ $appset.appName }}.yaml'
            valuesObject:
              {{- with index $.Values.addonsConfig.default $appset.appName }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            # Special handling for Datadog configuration
            {{ if eq $appset.appName "datadog" }}
            parameters:
              - name: 'datadog.apiKeyExistingSecret'
                value: '{{`{{.name}}`}}'
              - name: 'datadog.clusterName'
                value: '{{`{{.name}}`}}'
              - name: 'datadog.env[0].name'
                value: DD_ENV
              - name: 'datadog.env[0].value'
                value: {{ $environment.env }}
            {{ end }}
        # Secondary source - reference to values repository
        - repoURL: {{ $.Values.repoURL }}
          targetRevision: HEAD
          ref: values
      destination:
        # Special handling for control plane environment
        # When env is "argocd-control-plane", deploy to the local cluster
        # This is used primarily for ESO installation on the ArgoCD cluster
        {{- if eq $environment.env "argocd-control-plane" }}
        server: https://kubernetes.default.svc
        {{- else }}
        server: '{{`{{.server}}`}}'
        {{- end }}
        namespace: {{ $appset.appName }}
      syncPolicy:  
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
      {{- with $appset.ignoreDifferences }}
      ignoreDifferences:
      {{- toYaml . | nindent 8 }}
      {{- end }}        
---
{{- end }}
{{- end }}