apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: cluster-addons-root
  name: cluster-addons-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - "../../values/addons-list.yaml"
    path: charts/cluster-addons
    repoURL: 'https://github.com/MoranWeissman/msd-meetup-argocd-2023.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true