apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretManagerRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.esoServiceAccount }}
            namespace: {{ .Values.esoNamespace }}
